### PR TITLE
fix(community_partners): make speakers and community partners alignment to horizontal

### PR DESCRIPTION
**Pull request by suryahanumandla**
A quick fix to make speakers and community partners alignment to horizontal, only flaw is it adds horizontal scroll
image
image

#### Suggestion 1:
I feel scroll is not a good idea, we can make multiple containers and show the speakers and community partners in multiple sections. It would look like this

image
image

#### Suggestion 2:
We can make use of any carousel library

### CODE REVIEW

**Comment by inovizz** [comment]
Thank you for your contribution @suryahanumandla. I really like suggestion 1 (multiple containers). 

Can you update your PR #68 to incorporate those changes?

**Comment by bhansa** [comment]
+1 for **suggestion 1**, it looks great.

**Comment by bhansa** [comment]
@suryahanumandla it will be great if this can be added today.

**Comment by suryahanumandla** [comment]
Sure @inovizz @bhansa

**Comment by suryahanumandla** [comment]
image

**Comment by suryahanumandla** [comment]
@bhansa for time being I've updated all community partner assets with same pixels and background.

**Comment by bhansa** [comment]
Okay @suryahanumandla, Is the preview looking good for community partners?

**Comment by bhansa** [comment]
Once done, please resolve the conflicts and we will be good for merge.

**Comment by suryahanumandla** [comment]
@bhansa will be fixing it in few mins

**Comment by suryahanumandla** [comment]
latest community partners looks like
image

**Comment by suryahanumandla** [comment]
@bhansa @inovizz please review it and let me know if any changes needed.

**Review by inovizz — APPROVED** [review]

**Comment by inovizz** [comment]
Apparently, I merged the PR and then realized that the mobile view had CSS issues. So had to revert the merge.

Could you please fix the issues in mobile and re-open the PR.

Sorry for the trouble.

@suryahanumandla

**Comment by suryahanumandla** [comment]
@inovizz 
I haven't verified mobile view. sure will look into it.

**Pull request merged**
